services:
  db:
    image: postgres:17.1
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tarasPG']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  db-data:
